openapi: "3.1.0"

info:
  title: Morfi Core API
  version: 1.0.0

  description: >
    # Introduction

    This documentation was written following OpenAPI specification descripted [here](https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/versions/3.0.0.md).
    It was further **extended** by [ReDoc](https://github.com/Redocly/redoc) Team.

components:
  schemas:
    BaseGet:
      $ref: 'resources/schemas.yml#/components/schemas/BaseGet'
    AccessToken:
      $ref: 'resources/entities.yml#/components/schemas/AccessToken'
    RefreshToken:
      $ref: 'resources/entities.yml#/components/schemas/RefreshToken'
    Registration:
      $ref: 'resources/entities.yml#/components/schemas/Registration'
    CustomError:
      $ref: 'resources/entities.yml#/components/schemas/CustomError'



  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer


paths:
  /auth/registrations:

    # Auth 01. Registration

    post:
      summary: 01. Registration
      description: Creates a new user in the system. The user will remain inactive until an activation post was submitted.
      tags:
        - Auth

      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - first_name
              properties:
                email:
                  type: string
                  example: john@doe.com
                  maxLength: 150
                password:
                  type: string
                  example: "1234ABCD##"
                  maxLength: 128
                  minLenght: 8
                first_name:
                  type: string
                  maxLength: 50
                  example: John
                last_name:
                  type: string
                  maxLength: 50
                  example: Doe


      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#components/schemas/BaseGet'
                  - type: object
                    properties:
                      data:
                        $ref: '#components/schemas/Registration'
        400:
          description: BAD REQUEST
        500:
          $ref: resources/responses.yaml#InternalServerError

  /auth/activations:

    # Auth 02. Activation

    post:
      summary: 02. Activation
      description: Activates a user using the recived activation code.
      tags:
        - Auth

      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - code
              properties:
                email:
                  type: string
                  example: john@doe.com
                  maxLength: 150
                code:
                  type: string
                  maxLength: 10
                  example: ABCDE12345

      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#components/schemas/BaseGet'
                  - type: object
                    properties:
                      data:
                        $ref: '#components/schemas/Registration'
        400:
          description: BAD REQUEST
        404:
          description: NOT FOUND
        500:
          $ref: resources/responses.yaml#InternalServerError

  /auth/tokens:

    # Auth 03. Login

    post:
      summary: 03. Login
      description: Creates an access token for a given user.
      tags:
        - Auth

      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: john@doe.com
                  maxLength: 150
                password:
                  type: string
                  example: "1234ABCD##"
                  maxLength: 128
                  minLenght: 8

      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#components/schemas/BaseGet'
                  - type: object
                    properties:
                      data:
                        $ref: '#components/schemas/AccessToken'
        400:
          description: BAD REQUEST
        401:
          description: UNAUTHORIZED
        500:
          $ref: resources/responses.yaml#InternalServerError

    # Auth 04. Refresh Access Token

    put:

      summary: 04.  Refresh
      description: Refreshes an access token using the stored refresh_token value.
      tags:
        - Auth
      security:
        - BearerAuth: []

      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#components/schemas/BaseGet'
                  - type: object
                    properties:
                      data:
                        $ref: '#components/schemas/RefreshToken'
        500:
          $ref: resources/responses.yaml#InternalServerError

    # Auth 05. Logout

    delete:
      summary: 05. Logout
      description: Deletes an access token and its refresh token
      tags:
        - Auth

      security:
        - BearerAuth: []

      responses:
        204:
          description: NO CONTENT
        401:
          description: UNAUTHORIZED
        500:
          $ref: resources/responses.yaml#InternalServerError

  /auth/passwords/reset:

    # Auth 06. Reset

    post:
      summary: 06. Password reset
      description: Initiates password reseting process
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: john@doe.com
                  maxLength: 150
                  minLenght: 8

      responses:
        204:
          description: NO CONTENT
        500:
            $ref: resources/responses.yaml#InternalServerError

  /auth/passwords:

    # Auth 07. Password update

    post:
      summary: 07. Password update
      description: Complete the password reset
      tags:
        - Auth

      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - password
              properties:
                token:
                  type: string
                  example: eyJpZCI6MX0.Y_vmsw.D9TLmDOsllVhZJcQHB1e4rMQr4M
                password:
                  type: string
                  example: "1234ABCD##"
                  maxLength: 128
                  minLenght: 8

      responses:
        201:
          description: CREATED
        500:
            $ref: resources/responses.yaml#InternalServerError

